server:
  port: 8001
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true

  mail:
    host: smtp.qq.com  #设置邮箱类型
    username: yourEmail       #邮箱地址
    password: yourSmtpToken   #授权码
    default-encoding: UTF-8
  data:
    mongodb:
      database: blog_article        #mongodb数据库名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT%2B8

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hnust.zsg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false